name: Last
options:
  bundleIdPrefix: neo.uniwalls
  deploymentTarget:
    iOS: "17.0"
targets:
  Last:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - SourceCode.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: neo.uniwalls
        DEVELOPMENT_TEAM: VYB7C529CN
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Development"
        PROVISIONING_PROFILE_SPECIFIER: "Developer"
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "This app needs access to your photo library to attach images."